databases:
  - name: TagUp
    databaseName: TagUp
    user: TagUp

services:
  - type: web
    name: TagUp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TagUp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false